### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by alderson59** [calendso/calendso#1123]
### Issue Summary
<details><summary>Logs</summary>

```
(Use `node --trace-warnings ...` to show where the warning was created)
(node:169) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 58)
(node:169) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[next-auth][error][client_fetch_error] 
https://next-auth.js.org/errors#client_fetch_error session FetchError: request to https://calendso.domain.com/api/auth/session failed, reason: getaddrinfo EAI_AGAIN calendso.domain.com
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
prisma:query SELECT "public"."users"."id", "public"."users"."username", "public"."users"."name", "public"."users"."email", "public"."users"."emailVerified", "public"."users"."password", "public"."users"."bio", "public"."users"."avatar", "public"."users"."timeZone", "public"."users"."weekStart", "public"."users"."startTime", "public"."users"."endTime", "public"."users"."bufferTime", "public"."users"."hideBranding", "public"."users"."theme", "public"."users"."created", "public"."users"."completedOnboarding", "public"."users"."locale", "public"."users"."twoFactorSecret", "public"."users"."twoFactorEnabled", "public"."users"."plan" FROM "public"."users" WHERE "public"."users"."email" = $1 LIMIT $2 OFFSET $3
(node:169) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at hkdf_extract (/app/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/app/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/app/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/app/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/app/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(node:169) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 146)
```

</details>

Unable to login.

Not sure why EAI_AGAIN shows. Docker container can reach internet, the calendso instance is reachable at https://calendso.domain.com (not my actual domain of course). URL is HTTPS-forced.

What else is needed when creating a new user? No further details specified in instructions. I added only user, name, email, password (encrypted with Bcrypt)

### Steps to Reproduce

1. Based on the instructions on github readme to create a new user with prisma studio (already encrypted password with bcrypt)
2. Logging in causes logs above to show.
3. Logging in stuck at the box filling up loading screen, and then subsequently shows up with "something went wrong" error in red text on web UI

### Technical
Using https://github.com/calendso/docker
- changed both BASE_URL and NEXTAUTH_URL to https://calendso.domain.com

**Comment by alderson59** [comment]
Didn't realise Google Calendar API is needed, since I didn't plan on using Google Calendar. Is this necessary? I added it anyway just in case the error was throwing due to this, but it still had similar issues as above logs.

**Comment by bjornvdakker** [comment]
Same issue here, deployed on Railway. Logs:

```
prisma:query SELECT "public"."users"."id", "public"."users"."username", "public"."users"."name", "public"."users"."email", "public"."users"."emailVerified", "public"."users"."password", "public"."users"."bio", "public"."users"."avatar", "public"."users"."timeZone", "public"."users"."weekStart", "public"."users"."startTime", "public"."users"."endTime", "public"."users"."bufferTime", "public"."users"."hideBranding", "public"."users"."theme", "public"."users"."created", "public"."users"."completedOnboarding", "public"."users"."locale", "public"."users"."twoFactorSecret", "public"."users"."twoFactorEnabled", "public"."users"."plan" FROM "public"."users" WHERE "public"."users"."email" = $1 LIMIT $2 OFFSET $3
[next-auth][warn][jwt_auto_generated_signing_key] 
https://next-auth.js.org/warnings#jwt_auto_generated_signing_key
(node:37) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at hkdf_extract (/workspace/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/workspace/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/workspace/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/workspace/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/workspace/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/workspace/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
```

**Comment by airplanenoise** [comment]
i am also experiencing this issue on railway 

`(node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 990)`

**Comment by Cobular** [comment]
I am also seeing the same exact log statement as @bjornvdakker 
```
+ /app/scripts/wait-for-it.sh -- echo 'db is up'
Error: you need to provide a host and port to test.
Usage:
  /app/scripts/wait-for-it.sh host:port|url [-t timeout] [-- command args]
  -q | --quiet                        Do not output any status messages
  -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
  -- COMMAND ARGS                     Execute command with args after the test finishes
+ npx prisma migrate deploy
+ yarn start
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
[next-auth][warn][jwt_auto_generated_signing_key] 
https://next-auth.js.org/warnings#jwt_auto_generated_signing_key
(node:162) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at hkdf_extract (/app/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/app/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/app/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/app/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/app/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 104)
(node:162) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:162) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at hkdf_extract (/app/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/app/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/app/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/app/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/app/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(node:162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 147)
(node:162) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at hkdf_extract (/app/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/app/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/app/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/app/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/app/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(node:162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 204)
(node:162) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at hkdf_extract (/app/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/app/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/app/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/app/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/app/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(node:162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 236)
(node:162) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at hkdf_extract (/app/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/app/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/app/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/app/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/app/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(node:162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 268)```

**Comment by Cobular** [comment]
Update: see #856, that solved it. You need to add a `JWT_SECRET` env var. I'll try to PR something into the docker repo soon to get it's env file up to speed.

**Comment by JakeCooper** [comment]
Indeed seeing this issue on Railway. Might be good to have a fallback secret generated automagically and stored inside the DB on first run?

https://discord.com/channels/713503345364697088/908039242167509054/908055005452439624

**Comment by ConnorGargano** [comment]
I have closed this issue for now as it looks like a resolution has been found.
