### ISSUE TITLE
Server Error while logging out

### ISSUE THREAD

**Issue by rittmang** [calendso/calendso#13]
## Expected Behavior
1. Logout and redirect to login page, when user clicks on logout button

## Current Behavior
![image](https://user-images.githubusercontent.com/28761428/114872017-85228300-9e17-11eb-97ec-9a5b13f01e00.png)
on Chrome, with server currently on localhost.
username, name, email, password, bio are filled in DB. Besides startTime, endTime, createdDate,eventTypes and credentials.

## Error Log
TypeError: Cannot read property 'user' of null
    at getServerSideProps (webpack-internal:///./pages/settings/profile.tsx:429:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async renderToHTML (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/render.js:40:215)
    at async /home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/next-server.js:109:97
    at async /home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/next-server.js:102:142
    at async DevServer.renderToHTMLWithComponents (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/next-server.js:134:387)
    at async DevServer.renderToHTML (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/next-server.js:135:522)
    at async DevServer.renderToHTML (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/next-server.js:72:236)
    at async Object.fn (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/next-server.js:56:580)
    at async Router.execute (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async DevServer.handleRequest (/home/ritom/Desktop/Projects/calendso/node_modules/next/dist/next-server/server/next-server.js:34:504)

**Comment by baileypumfleet** [comment]
Indeed, this is a known issue. Basically, we just need to instruct Next-Auth.js to redirect back to the login page when a user logs out.

**Comment by emrysal** [comment]
Nothing special needs to happen when you click the logout button, just unset the session. Then in the Shell component add middleware checking for a valid session; which if found to be missing can then redirect to /login.

See: https://github.com/vercel/next.js/discussions/14945

**Comment by rittmang** [comment]
I tried deploying the app to Heroku as well. This error does seem to come up as some sort of error while I logged out (for a split second) but it immediately redirected to login page by itself, maybe because it's a production build instead of dev?

**Comment by baileypumfleet** [comment]
This is fixed in the latest commit, as the logout links now point to logoutHandler, which calls signOut() and then redirects to /
