### ISSUE TITLE
Crash when username does not exist

### ISSUE THREAD

**Issue by PabloCastellano** [calendso/calendso#144]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Error 500 is returned, see traceback below. It should return 404 as `https://CALENDSO_URI/unexisting/`  does.

```
TypeError: Cannot read property 'id' of null
    at getServerSideProps (/home/pablo/calendso/.next/server/pages/[user]/[type].js:2974:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async renderToHTML (/home/pablo/calendso/node_modules/next/dist/next-server/server/render.js:40:215)
    at async /home/pablo/calendso/node_modules/next/dist/next-server/server/next-server.js:111:97
    at async /home/pablo/calendso/node_modules/next/dist/next-server/server/next-server.js:104:142
    at async Server.renderToHTMLWithComponents (/home/pablo/calendso/node_modules/next/dist/next-server/server/next-server.js:136:387)
    at async Server.renderToHTML (/home/pablo/calendso/node_modules/next/dist/next-server/server/next-server.js:137:1088)
    at async Server.render (/home/pablo/calendso/node_modules/next/dist/next-server/server/next-server.js:74:255)
    at async Object.fn (/home/pablo/calendso/node_modules/next/dist/next-server/server/next-server.js:58:672)
    at async Router.execute (/home/pablo/calendso/node_modules/next/dist/next-server/server/router.js:25:67)
```

### Steps to Reproduce
1. Go to `https://CALENDSO_URI/unexisting/type`

### Technical details
* Browser Firefox
* Node.js 14.16

**Comment by emrysal** [comment]
Fixed in incoming PR #132
