### ISSUE TITLE
GoogleCalendarService not using destination calendar id for deleting event

### ISSUE THREAD

**Issue by philprime** [calendso/calendso#1481]
### Issue Summary

When deleting a booking with an associated Google calendar event in a custom destination calendar, the API call fails to delete the event.

This is caused, because the API call to delete the Google calendar event is always using the `primary` calendar, instead of the calendar where the event is actually located at.

This is the HTTP URL currently used (example calendar event):

`https://www.googleapis.com/calendar/v3/calendars/primary/events/jqb61qvnh1udfv74vgtkrt1luk`

This is the URL is should be (redacted the full calendar name):

`https://www.googleapis.com/calendar/v3/calendars/c_ll5ue0re...@group.calendar.google.com/events/jqb61qvnh1udfv74vgtkrt1luk`

### Steps to Reproduce

1. Setup a Google calendar integration
2. Define a custom calendar as the destination calendar
3. Create a new booking
4. Cancel the booking from the management dashboard
5. You should see an error in the browser and in the log

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

Excerpt of the error:

```
# Error

GaxiosError: Not Found
    at Gaxios._request (/app/node_modules/gaxios/build/src/gaxios.js:129:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MyGoogleAuth.requestAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18) {
  response: {
    config: {
      url: 'https://www.googleapis.com/calendar/v3/calendars/primary/events/es6cd4qq7otkq885m5pnb9n7g8?sendNotifications=true&sendUpdates=all',
      method: 'DELETE',
      userAgentDirectives: [Array],
      paramsSerializer: [Function (anonymous)],
      headers: [Object],
      params: [Object],
      validateStatus: [Function (anonymous)],
      retry: true,
      responseType: 'json',
      retryConfig: [Object]
    },
    data: { error: [Object] },
    headers: {
        ...
    },
    status: 404,
    statusText: 'Not Found',
    request: {
      responseURL: 'https://www.googleapis.com/calendar/v3/calendars/primary/events/es6cd4qq7otkq885m5pnb9n7g8?sendNotifications=true&sendUpdates=all'
    }
  },
  config: {
    url: 'https://www.googleapis.com/calendar/v3/calendars/primary/events/es6cd4qq7otkq885m5pnb9n7g8?sendNotifications=true&sendUpdates=all',
    method: 'DELETE',
    userAgentDirectives: [ [Object] ],
    paramsSerializer: [Function (anonymous)],
    headers: {
      'x-goog-api-client': 'gdcl/5.0.5 gl-node/14.18.2 auth/7.10.2',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/5.0.5 (gzip)',
      Authorization: 'Bearer [REDACTED]',
      Accept: 'application/json'
    },
    params: { sendNotifications: true, sendUpdates: 'all' },
    validateStatus: [Function (anonymous)],
    retry: true,
    responseType: 'json',
    retryConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  },
  code: 404,
  errors: [ { domain: 'global', reason: 'notFound', message: 'Not Found' } ]
}
```

The database contains the following data:

**User**
| id | username |
|---|---|
| 1 | phil |

**DestinationCalendar**
| id | integration | externalId | userId |
|---|---|---|---|
| 1 | google_calendar | c_ll5ue0re275kq...@group.calendar.google.com | 1 |

**Booking**
| id | uid | userId | eventTypeId
|---|---|---|---|
| 23 | f7j5VWvkQT3JAuz9pTzAn5 | 1 | 3

**BookingReference**
| id | type | uid | bookingId | meetingId
|---|---|---|---|---|
| 24 | google_calendar | es6cd4qq7otkq885m5pnb9n7g8 | 23 | es6cd4qq7otkq885m5pnb9n7g8 |

The issue is right here in `GoogleCalendarService.ts#L198`. Instead of using the `primary` calendar, it should use the one defined by the event. For reference, this is already implemented in the `updateEvent` method.

https://github.com/calendso/calendso/blob/70683a89b9fcf86f4ce140ca121cf6f96b834c71/lib/integrations/calendar/services/GoogleCalendarService.ts#L188-L213

I might be able to provide a PR, but need to look further into it.

**Comment by philprime** [comment]
Even tough PR #1486 fixes the issue, it is not an elegant solution.

Instead the calendar id should be stored with the BookingReference to the external event.

A Google Calendar event is uniquely identified by `calendarId` and `eventId`

**Comment by zomars** [comment]
First of all I must say I'm impressed with this bug report. Thank you so much for taking the time for doing this. Looking into your PR #1486 and some things come to my mind.

First, we should make sure every calendar integration (Apple, CalDav, Google and Office) has the expected behavior when deleting an event.

> Instead the calendar id should be stored with the BookingReference to the external event.

Could do elaborate on this? Agreed we can always handle this in a more elegant way.

**Comment by philprime** [comment]
Right now the application tries to delete the Google event in the `primary` calendar instead of the actual calendar where the event is located in. e.g. `my-cal`.

My PR is more a quick fix, to validate the solution. Instead of `primary` it uses the destination calendar of the user, and "hopes" that is the correct one. This could still fail if we change the destination calendar to another one.

Steps:

1. Add Google Integration with 3 calendars: `primary`, `my-cal-1` and `some-cal-2`
2. Select `my-cal-1` as the destination calendar
3. Create a booking --> `event-1` is created in `my-cal-1`
4. Delete the booking --> with my PR it would be able to delete the event `event-1`, because event-calendar = destination-calendar
5. Create another booking --> `event-2` is created in `my-cal-1`
6. Change the destination calendar to `some-cal-2`
7. Delete the booking --> API call fails, because the event `event-2`, because event-calendar != destination-calendar and event-calendar != primary-calendar

Instead of implicitly assuming that the event is located in the `primary` or `destination-calendar`, we should store it with the BookingReference. 

**BookingReference**
| id | type | uid | bookingId | meetingId | **calendarId** |
|---|---|---|---|---|---|
| 24 | google_calendar | es6cd4qq7otkq885m5pnb9n7g8 | 23 | es6cd4qq7otkq885m5pnb9n7g8 | **some-cal-2** |

Here is the relevant Google Calendar API documentation:

https://developers.google.com/calendar/api/v3/reference/events/get

As you can see, it always requires an `eventId` **and** a `calendarId` to identify an event.
