### ISSUE TITLE
Lack of client side validation for event type creation

### ISSUE THREAD

**Issue by rymaju** [calendso/calendso#157]
### Issue Summary

Relevant issue: #143 

When creating an event with no event length an API request is still sent, generating a prisma error
```
PrismaClientValidationError:
Invalid `prisma.eventType.create()` invocation:

{
  data: {
    title: '1on1',
    slug: 'hi',
    description: '',
    length: NaN,
            ~~~
    hidden: false,
    userId: 1
  }
}

Argument length: Got invalid value NaN on prisma.createOneEventType. Provided Float, expected Int.


    at Document.validate (C:\Users\forry\Documents\Code\js\calendso\node_modules\@prisma\client\runtime\index.js:32462:19)
    at NewPrismaClient._executeRequest (C:\Users\forry\Documents\Code\js\calendso\node_modules\@prisma\client\runtime\index.js:34399:17)
    at C:\Users\forry\Documents\Code\js\calendso\node_modules\@prisma\client\runtime\index.js:34334:52
    at AsyncResource.runInAsyncScope (async_hooks.js:186:9)
    at NewPrismaClient._request (C:\Users\forry\Documents\Code\js\calendso\node_modules\@prisma\client\runtime\index.js:34334:25)
    at Object.then (C:\Users\forry\Documents\Code\js\calendso\node_modules\@prisma\client\runtime\index.js:34454:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clien...
```
![image](https://user-images.githubusercontent.com/23691775/117212038-caf3bb00-adc7-11eb-8274-a99087cc984c.png)

Creating a new event should perform client side validation to prevent 500 errors, in addition no error message is shown, so the user cant tell why their event type creation isnt working :/
### Steps to Reproduce
1. Logged in
2. Attempted to create event type without meeting length
3. 500 error from prisma

Instead I expected to get some errors on the client side, either an actual error message or some client side validation.

**Comment by rymaju** [comment]
Currently working on a quick client side fix to prevent this, although I think there should probably be an error message displayed on non 2XX responses in the future.
