### ISSUE TITLE
Error: Invalid key length - Apple Calendar Integration

### ISSUE THREAD

**Issue by davidwuest** [calendso/calendso#1585]
When trying to add the apple calendar I get the following error. Any ideas?
Error: Invalid key length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at symmetricEncrypt (/app/.next/server/chunks/1027.js:29:66)
    at handler (/app/.next/server/pages/api/integrations/apple/add.js:145:88)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/app/node_modules/next/dist/server/next-server.js:1064:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:951:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:222:32)

**Comment by Dax911** [comment]
Yes I have the same error.

**Comment by davidwuest** [comment]
@Dax911 thank you for your feedback. Just trying to narrow it down. I'm currently using a self signed certificate, since I'm on a test server. Are you using a self-signed or trusted certificate?

**Comment by milospuac** [comment]
Hey David! Thanks for sending this to us. Our calendar is working on the Apple Calendar integration issues, and I'll give you an update once sorted.

**Comment by 7d916724** [comment]
@davidwuest - can you confirm that the `CALENDSO_ENCRYPTION_KEY` environment variable is defined? I was able to recreate this error by leaving that env variable empty.

You can see [here](https://github.com/calendso/calendso/blob/main/pages/api/integrations/apple/add.ts#L33) that the code expects `process.env.CALENDSO_ENCRYPTION_KEY` to not be null.

**Comment by davidwuest** [comment]
@7d916724 - I had the `CALENDSO_ENCRYPTION_KEY` environment variable defined, but not in the correct length. Regenerated and it worked. Thanks for pointing it out.

**Comment by ankit-io** [comment]
Hi @davidwuest, what is the correct length?

**Comment by davidwuest** [comment]
> Hi @davidwuest, what is the correct length?

Just do `dd if=/dev/urandom bs=1K count=1 | md5sum`

**Comment by charleslcso** [comment]
> > Hi [@davidwuest](https://github.com/davidwuest), what is the correct length?
> 
> Just do `dd if=/dev/urandom bs=1K count=1 | md5sum`

This works. I no longer get the `RangeError: Invalid key length`, unlike the official command `openssl rand -base64 32`.

Weird.
