### ISSUE TITLE
Getting error on node 14

### ISSUE THREAD

**Issue by asharabu** [calendso/calendso#210]
Hi,

I am getting below error on node 14,

![image](https://user-images.githubusercontent.com/42669995/119003377-4d28d580-b9ab-11eb-89d3-3c44fd3ae84c.png)

> 

https://next-auth.js.org/warnings#jwt_auto_generated_signing_key
TypeError: Cannot read property 'id' of null
    at getServerSideProps (webpack-internal:///./pages/index.tsx:779:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async renderToHTML (/opt/app/node_modules/next/dist/next-server/server/render.js:40:215)
    at async /opt/app/node_modules/next/dist/next-server/server/next-server.js:111:97
    at async /opt/app/node_modules/next/dist/next-server/server/next-server.js:104:142
    at async DevServer.renderToHTMLWithComponents (/opt/app/node_modules/next/dist/next-server/server/next-server.js:136:387)
    at async DevServer.renderToHTML (/opt/app/node_modules/next/dist/next-server/server/next-server.js:137:610)
    at async DevServer.renderToHTML (/opt/app/node_modules/next/dist/server/next-dev-server.js:36:578)
    at async DevServer.render (/opt/app/node_modules/next/dist/next-server/server/next-server.js:74:255)
    at async Object.fn (/opt/app/node_modules/next/dist/next-server/server/next-server.js:58:672)
    at async Router.execute (/opt/app/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/opt/app/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async DevServer.handleRequest (/opt/app/node_modules/next/dist/next-server/server/next-server.js:32:504)

>

**Comment by baileypumfleet** [comment]
Did you push the Prisma schema to the database?

**Comment by asharabu** [comment]
@baileypumfleet Yes, I have done it by executing the command `npx prisma db push --preview-feature`.

**Comment by baileypumfleet** [comment]
Can you try again using the latest codebase?

**Comment by asharabu** [comment]
@baileypumfleet Now the calendso URL is getting up. But the prisma URL showing error. We tried in both 14.16 and 14.17 node versions.
![image](https://user-images.githubusercontent.com/42669995/119818851-56ff8b00-bf0d-11eb-9390-deed04b9e5ad.png)

**Comment by visibleajay** [comment]
Please share the steps to reproduce. Working fine for me. Also, Please check if its working with other node versions like `v12.18.3` just to be sure if its a `node` version issue.

MacOs
Node v14.17.0.

**Comment by visibleajay** [comment]
@asharabu  Please refer `https://www.youtube.com/watch?v=TaIQhG8AL0w&t=897s`

**Comment by asharabu** [comment]
@visibleajay Prisma studio worked when upgraded version to the latest Prisma version 2.24.0. Please consider to update the same in packages.json
