### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by cpanato** [calendso/calendso#368]
### Issue Summary
Cannot login

When I try to login in the application I got this error log

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
[next-auth][warn][jwt_auto_generated_signing_key]
https://next-auth.js.org/warnings#jwt_auto_generated_signing_key
(node:222) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
    at ServerResponse.setHeader (_http_outgoing.js:564:3)
    at ServerResponse.res.redirect (/app/node_modules/next-auth/dist/server/lib/extend-res.js:39:21)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:331:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:222) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
If I remove the `NEXTAUTH_URL` it redirect to the `localhost:3000`, if I add that to my domain I got the error above

I was able to login doing a very hack thing

1. Start the docker-compose in the calendso-docker
2. remove the `NEXTAUTH_URL` from my deployment
3. login in my production deployment, it redirect to my local deployment (where I've configured the same user) 
4. reopen the production deployment page and then I was able to login
🙈 

### Steps to Reproduce

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: https://www.whatsmybrowser.org/b/99U31
* Node.js node:14

**Comment by baileypumfleet** [comment]
Could you share your BASE_URL and NEXTAUTH_URL environment variables?

**Comment by cpanato** [comment]
@baileypumfleet 
BASE_URL points to my domain: https://calendso.cpanato.dev
NEXTAUTH_URL was the same

**Comment by PeerRich** [comment]
can you try again?

**Comment by cpanato** [comment]
@PeerRich will get the lastest main branch and build /deploy, will let you know thanks!

**Comment by cpanato** [comment]
now everything works! thanks!

**Comment by pratikbalar** [comment]
Getting in docker environment when login
```log
prisma:query SELECT "public"."users"."id", "public"."users"."username", "public"."users"."name", "public"."users"."email", "public"."users"."emailVerified", "public"."users"."password", "public"."users"."bio", "public"."users"."avatar", "public"."users"."timeZone", "public"."users"."weekStart", "public"."users"."startTime", "public"."users"."endTime", "public"."users"."bufferTime", "public"."users"."hideBranding", "public"."users"."theme", "public"."users"."created", "public"."users"."completedOnboarding", "public"."users"."locale", "public"."users"."twoFactorSecret", "public"."users"."twoFactorEnabled", "public"."users"."plan" FROM "public"."users" WHERE "public"."users"."email" = $1 LIMIT $2 OFFSET $3
[next-auth][warn][jwt_auto_generated_signing_key] 
https://next-auth.js.org/warnings#jwt_auto_generated_signing_key
(node:217) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at hkdf_extract (/app/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/app/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/app/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/app/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/app/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 66)
(node:217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

envs

```env
POSTGRES_USER=unicorn_user
POSTGRES_PASSWORD=magical_password
POSTGRES_DB=calendso
DATABASE_HOST=db:5432
DATABASE_URL="postgresql://unicorn_user:magical_password@db:5432/calendso"
GOOGLE_API_CREDENTIALS=''
BASE_URL='http://localhost:3000'
NEXTAUTH_URL='http://localhost:3000'
```
