### ISSUE TITLE
Canceling an event that was already canceled returns a 500 error

### ISSUE THREAD

**Issue by codedeeply** [calendso/calendso#387]
### Issue Summary
If you re-visit the link to cancel an event that's already been canceled, it returns a 500 internal server error. It might be more useful from a user/client perspective to display a message that the requested meeting was already canceled to avoid confusion. (i.e. the calendar owner cancels the event after external communication with invitee, and then the invitee tries to click the cancel link on their end as well).

Thank you!

### Steps to Reproduce
1. Schedule a meeting as normal
2. Click the link to cancel it, either in the email or on the "Bookings" backend page
3. Cancel meeting
4. Click same link from Step 2 again

Error log details:
```
TypeError: Cannot read property 'startTime' of null
    at getServerSideProps (/app/.next/server/pages/cancel/[uid].js:227:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)
    at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:1088)
    at async Server.render (/app/node_modules/next/dist/next-server/server/next-server.js:75:160)
    at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:58:672)
TypeError: Cannot read property 'user' of null
    at getServerSideProps (/app/.next/server/pages/reschedule/[uid].js:48:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)
    at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:1088)
    at async Server.render (/app/node_modules/next/dist/next-server/server/next-server.js:75:160)
    at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:58:672)
```

### Technical details
* Browser version: Chrome 91 (https://www.whatsmybrowser.org/b/FO88M)
* Node.js version: 14.17.3
* This is running off guestros/calendso-githubbuild:latest

**Comment by joshsny** [comment]
@PeerRich We can close this, since the above PR has been merged :)

**Comment by codedeeply** [comment]
Thank you!!
