### ISSUE TITLE
Can't create an appointment

### ISSUE THREAD

**Issue by ilovefreesw** [calendso/calendso#42]
I get the following on the console after I select the date. It won't let me select time...it just keeps spinning.

![image](https://user-images.githubusercontent.com/77317006/115106247-532d3000-9f81-11eb-822f-cdf2d53cb982.png)

```
TypeError: Cannot read property '0' of undefined
    at authorise (webpack-internal:///./pages/api/availability/[user].ts:32:88)
    at handler (webpack-internal:///./pages/api/availability/[user].ts:24:3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async apiResolver (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async DevServer.handleApiRequest (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/next-server.js:64:462)
    at async Object.fn (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/next-server.js:56:492)
    at async Router.execute (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async DevServer.handleRequest (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/next-server.js:34:504)
TypeError: Cannot read property '0' of undefined
    at authorise (webpack-internal:///./pages/api/availability/[user].ts:32:88)
    at handler (webpack-internal:///./pages/api/availability/[user].ts:24:3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async apiResolver (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async DevServer.handleApiRequest (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/next-server.js:64:462)
    at async Object.fn (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/next-server.js:56:492)
    at async Router.execute (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async DevServer.handleRequest (/home/testo101/test/calendso/node_modules/next/dist/next-server/server/next-server.js:34:504)
```
OS: Windowsfx (Ubuntu 20,04 LTS)
Node: v14.16.1
Yarn: 1.22.10

**Comment by baileypumfleet** [comment]
I would suggest checking the OAuth related stuff for the Google Calendar first
