### ISSUE TITLE
Invalid time zone

### ISSUE THREAD

**Issue by deeztek** [calendso/calendso#559]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
RangeError: Invalid time zone specified: Eastern Standard Time

### Steps to Reproduce
1. Create Caldav connection
2. Create event
3. Goto event page and try to select a day, website displays following error:

`Could not load the available time slots`

In addition, container logs display the following error:

```
7145.js:281 getAvailability
    .next/server/chunks/7145.js:281:27
• [user].js:43 handler
    .next/server/pages/api/availability/[user].js:43:29
RangeError: Invalid time zone specified: Eastern Standard Time

  at Date.toLocaleString (<anonymous>)
    at M.f.tz (/app/node_modules/dayjs/plugin/timezone.js:1:1035)
    at /app/.next/server/chunks/7145.js:344:110
    at Array.map (<anonymous>)
    at CalDavCalendar.getEvents (/app/.next/server/chunks/7145.js:337:115)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CalDavCalendar.getAvailability (/app/.next/server/chunks/7145.js:281:27)
    at async Promise.all (index 0)
    at async handler (/app/.next/server/pages/api/availability/[user].js:43:29)
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I'm expecting the event page to display available time slots. 

### Technical details
* Browser version: Chrome 91

**Comment by deeztek** [comment]
okay so it looks like I was able to get this to work by removing the caldav calendar and re-adding. However, I noticed that when browsing the event page, the Timezone is set to America/Detroit even though in calendso under Settings --> Profile --> Timezone I set it to (GMT-4:00) Eastern Time. That seems to get ignored and default to America/Detroit.
