### ISSUE TITLE
Issue creating bookings in Caldav

### ISSUE THREAD

**Issue by deeztek** [calendso/calendso#589]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When creating a booking in calendso, the event gets created in the caldav calendar however, no e-mails are sent out and no events get created with Zoom. 

### Steps to Reproduce
1. Goto event page
2. Click on desired date and time and create booking
3. Calendso reports "This meeting is scheduled"
4. Event gets created in caldav calendar
4. No confirmation e-mails are sent
5. No event is scheduled with Zoom

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect to get confirmation e-mails and I expected to get an event with Zoom

### Technical details
Following error appears in the logs:

22:28:15.722 timeZoneName ERROR [api] book:user Booking deeztek failed 

 TypeError  Cannot read property 'id' of undefined

error stack:

• 613.js:278 createMeeting

    .next/server/chunks/613.js:278:24

• 4605.js:76 create

    .next/server/chunks/4605.js:76:20

• 4605.js:640 handler

    .next/server/chunks/4605.js:640:29

• api-utils.ts:84 apiResolver

    node_modules/next/next-server/server/api-utils.ts:84:5

• next-server.ts:1168 handleApiRequest

    node_modules/next/next-server/server/next-server.ts:1168:5

• next-server.ts:1021 fn

    node_modules/next/next-server/server/next-server.ts:1021:27

• router.ts:346 execute

    node_modules/next/next-server/server/router.ts:346:24

• next-server.ts:1266 run

    node_modules/next/next-server/server/next-server.ts:1266:23

{ code: 124, message: 'Invalid access token.' }

Invalid JSON: SyntaxError: Unexpected token s in JSON at position 0

    at JSON.parse (<anonymous>)

    at validJson (/app/.next/server/pages/event-types/[type].js:437:20)

    at getServerSideProps (/app/.next/server/pages/event-types/[type].js:1779:57)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)

    at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97

    at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142

    at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)

    at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:1088)

SyntaxError: Unexpected token s in JSON at position 0

    at JSON.parse (<anonymous>)

    at validJson (/app/.next/server/pages/integrations.js:547:20)

    at getServerSideProps (/app/.next/server/pages/integrations.js:590:57)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)

    at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97

    at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142

    at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)

    at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:610)

Invalid JSON: SyntaxError: Unexpected token s in JSON at position 0

    at JSON.parse (<anonymous>)

    at validJson (/app/.next/server/pages/event-types/[type].js:437:20)

    at getServerSideProps (/app/.next/server/pages/event-types/[type].js:1779:57)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)

    at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97

    at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142

    at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)

    at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:1088)

SyntaxError: Unexpected token s in JSON at position 0

    at JSON.parse (<anonymous>)

    at validJson (/app/.next/server/pages/integrations.js:547:20)

    at getServerSideProps (/app/.next/server/pages/integrations.js:590:57)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)

    at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97

    at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142

    at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)

    at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:610)

SyntaxError: Unexpected token s in JSON at position 0

    at JSON.parse (<anonymous>)

    at validJson (/app/.next/server/pages/integrations.js:547:20)

    at getServerSideProps (/app/.next/server/pages/integrations.js:590:57)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)

    at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97

    at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142

    at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)

    at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:610)

**Comment by PeerRich** [comment]
hey @deeztek, we've forwarded this to our team who worked on CalDav. We're actively hiring for CalDav support, too to harden the integration 🙏

**Comment by deeztek** [comment]
Thanks for the heads up.
