### ISSUE TITLE
CalDav integration with Fastmail doesn't work

### ISSUE THREAD

**Issue by claudioruiz** [calendso/calendso#626]
### Issue Summary
It is not possible to connect calendso with a fastmail account 

### Steps to Reproduce
1. Connect calendso with a fastmail calendar
2. Create an event type
3. Fill a new event with a random email and user

Then, the event is created accordingly with calendso, but nothing is to be shown in the actual Fastmail calendar. It seems that there's no connection between calendso and Fastmail although the caldav account is perfectly set. Obviously, at the moment of selecting the time and date, calendso let you "schedule" even when that time and day is currently taken (same as #624)

### Technical details
* Browser version: https://www.whatsmybrowser.org/b/4HGZS
* Node.js version: v16.7.0
* the log:

```
13:55:25.341 timeZoneName DEBUG [api] book:user Booking chet completed
A body was attempted to be set with a 204 statusCode for /api/book/chet, this is invalid and the body was ignored.
See more info here https://nextjs.org/docs/messages/invalid-api-status-body
SEND_NEW_EVENT_NOTIFICATION_ERROR c@chet.com Error: Invalid login: 535 5.7.3 Authentication unsuccessful [SC1PR80CA0064.lamprd80.prod.outlook.com]
    at SMTPConnection._formatError (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:1536:34)
    at SMTPConnection.<anonymous> (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:1490:18)
    at SMTPConnection._processResponse (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'EAUTH',
  response: '535 5.7.3 Authentication unsuccessful [SC1PR80CA0064.lamprd80.prod.outlook.com]',
  responseCode: 535,
  command: 'AUTH LOGIN'
}
sendEmail Error: Error: Invalid login: 535 5.7.3 Authentication unsuccessful [SC1PR80CA0064.lamprd80.prod.outlook.com]
    at eval (webpack-internal:///./lib/emails/EventMail.ts:69:16)
    at /Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/mailer/index.js:226:21
    at /Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-transport/index.js:282:36
    at SMTPConnection._actionAUTHComplete (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:1536:20)
    at SMTPConnection.<anonymous> (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:1490:18)
    at SMTPConnection._processResponse (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
SEND_BOOKING_CONFIRMATION_ERROR clau@riseup.net Error: Invalid login: 535 5.7.3 Authentication unsuccessful [SC1PR80CA0067.lamprd80.prod.outlook.com]
    at SMTPConnection._formatError (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:1536:34)
    at SMTPConnection.<anonymous> (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:1490:18)
    at SMTPConnection._processResponse (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'EAUTH',
  response: '535 5.7.3 Authentication unsuccessful [SC1PR80CA0067.lamprd80.prod.outlook.com]',
  responseCode: 535,
  command: 'AUTH LOGIN'
}
sendEmail Error: Error: Invalid login: 535 5.7.3 Authentication unsuccessful [SC1PR80CA0067.lamprd80.prod.outlook.com]
    at eval (webpack-internal:///./lib/emails/EventMail.ts:69:16)
    at /Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/mailer/index.js:226:21
    at /Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-transport/index.js:282:36
    at SMTPConnection._actionAUTHComplete (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:1536:20)
    at SMTPConnection.<anonymous> (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:1490:18)
    at SMTPConnection._processResponse (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/cla/code/github/calendso-2021-08-31/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
```

**Comment by claudioruiz** [comment]
I can confirm that Fastmail/Caldav either doesn't work on the standalone cal.com version

**Comment by Cobular** [comment]
I'm also experiencing unsuccessful authorization issues with mailgun

**Comment by krzyzanowskim** [comment]
While it's possible to connect on hosted cal.com, but it's not functional apparently too
