### ISSUE TITLE
Error creating bookings

### ISSUE THREAD

**Issue by commandodev** [calendso/calendso#681]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When I create a booking, I have a booking in the database, but the calendar entry doesn't get created (and no email gets sent).

I'm running on railway with both the google and zoom integrations installed.

I see this in the logs:

```
14:50:36.267 timeZoneName DEBUG [api] book:user Booking eventType 1 started 
Error: Unauthorized
    at handleErrorsJson (/workspace/.next/server/chunks/8850.js:355:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async handler (/workspace/.next/server/pages/api/book/event.js:356:30)
    at async Object.apiResolver (/workspace/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/workspace/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/workspace/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/workspace/node_modules/next/dist/server/router.js:205:32)
    at async Server.run (/workspace/node_modules/next/dist/server/next-server.js:841:29)
    at async Server.handleRequest (/workspace/node_modules/next/dist/server/next-server.js:292:20)
TypeError: Cannot read property 'start' of undefined
    at /workspace/.next/server/pages/api/book/event.js:359:63
    at Array.map (<anonymous>)
    at handler (/workspace/.next/server/pages/api/book/event.js:358:51)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.apiResolver (/workspace/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/workspace/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/workspace/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/workspace/node_modules/next/dist/server/router.js:205:32)
    at async Server.run (/workspace/node_modules/next/dist/server/next-server.js:841:29)
    at async Server.handleRequest (/workspace/node_modules/next/dist/server/next-server.js:292:20)
{ code: 124, message: 'Invalid access token.' }
```

### Steps to Reproduce

I create a booking.
I see the booking in the app, but no emails are sent and the calendar entry isn't created.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
Running in railway - happy to screenshare set up if that would help.

**Comment by commandodev** [comment]
I tried deleting the zoom integration and now I get this as well:

`No suitable credentials given for the requested integration name.`
