### ISSUE TITLE
Self-hosted calendso fails to redirect to home after logging in

### ISSUE THREAD

**Issue by munjalpatel** [calendso/calendso#851]
### Issue Summary

After signing in, a session is generated. However, instead of getting redirected to the home page, the user is redirected back to `auth/login`

### Steps to Reproduce

1. Deploy on Railway using the `Deploy on Railway` button on https://github.com/calendso/calendso

2. Railway build will fail due to missing db tables. Do the following to resolve it:
```shell
git clone <repo-railway-created>
cd calendso
npm i -g @railway/cli
railway login
railway link
railway run npx prisma db push
```

3. Re-deploy on Railway

4. Add a new user using Railway's Postgres data explorer

5. Configure custom domain in Railway

6. Set up all of the following environment variables
![image](https://user-images.githubusercontent.com/2717686/135910334-dbb6f2a6-1470-4c6b-ae03-e3ee84983d5d.png)

** Make sure to set `Base_URL`, `NEXT_PUBLIC_APP_URL` and `NEXTAUTH_URL` to the custom domain in step 5 above.
```sh
# example
BASE_URL=https://cal.domain.com
NEXT_PUBLIC_APP_URL=https://cal.domain.com
NEXTAUTH_URL=https://cal.domain.com
```

7. Wait for the Railway deployment to complete and then try logging in by navigating to https://cal.domain.com

8. Notice the following:
- Instead of going to the home page, you are redirected to the login page again

- Notice logs in the Railway shows the following errors:
```
yarn run v1.22.15
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
[next-auth][error][client_fetch_error] 
https://next-auth.js.org/errors#client_fetch_error session FetchError: invalid json response body at https://cal.domain.com/api/auth/session reason: Unexpected token < in JSON at position 0
    at /workspace/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[next-auth][error][client_fetch_error] 
https://next-auth.js.org/errors#client_fetch_error session FetchError: invalid json response body at https://cal.domain.com/api/auth/session reason: Unexpected token < in JSON at position 0
    at /workspace/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[next-auth][error][client_fetch_error] 
https://next-auth.js.org/errors#client_fetch_error csrf FetchError: invalid json response body at https://cal.domain.com/api/auth/csrf reason: Unexpected token < in JSON at position 0
    at /workspace/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
```
- Inspect the browser's network request and ensure that the JWT and CSRF token is returned in the cookie despite the errors above

- Despite the errors above, notice that the user details are returned as a response to the `session` request

### Technical details

- Browser version: Chrome 94 ( https://www.whatsmybrowser.org/b/8CIY9 )

**Comment by munjalpatel** [comment]
@PeerRich any ideas?
